-- 159 — Yoga outcome nature (good/bad) and a one-line inference per yoga.
-- tbl_Rule_Yoga.OutcomeNatureCode (migration 48) was never populated. Each yoga is classified
-- from the result its source states: AUSPICIOUS (good), INAUSPICIOUS (bad), MIXED (good and bad
-- together, or a neutral description), CONTEXTUAL (no stated result). InferenceText is a short
-- paraphrase of that stated result: Raman, Three Hundred Important Combinations ("Results"
-- paragraph of each combination) for the 217 yogas it covers; PVR ch.11 for the 16 PVR-only
-- yogas; none for YOGA_ANIVAHUPPU (Horoscope Explorer structural predicate, no result).
-- Nature and inference are per YogaCode, so every rule row of a yoga (generic and
-- source-specific) gets the same values. vw_ChartYogaEvaluations exposes both.
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.tbl_Rule_Yoga','InferenceText') IS NULL
    ALTER TABLE dbo.tbl_Rule_Yoga ADD InferenceText NVARCHAR(300) NULL;
IF COL_LENGTH('dbo.tbl_Rule_Yoga','InferenceSourceRefCode') IS NULL
    ALTER TABLE dbo.tbl_Rule_Yoga ADD InferenceSourceRefCode VARCHAR(40) NULL;
IF COL_LENGTH('dbo.tbl_Rule_Yoga','InferenceSourceLocator') IS NULL
    ALTER TABLE dbo.tbl_Rule_Yoga ADD InferenceSourceLocator NVARCHAR(100) NULL;
COMMIT TRANSACTION;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @n TABLE (YogaCode VARCHAR(60) PRIMARY KEY, Nature VARCHAR(20) NOT NULL, Inference NVARCHAR(300) NOT NULL,
                  SourceRefCode VARCHAR(40) NULL, SourceLocator NVARCHAR(100) NULL);
INSERT @n VALUES
('YOGA_ADHI','AUSPICIOUS',N'Polite, trustworthy; a happy life in comfort and affluence, victory over enemies, good health and long life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 7'),
('YOGA_AMALA','AUSPICIOUS',N'Lasting fame and an unblemished character; a prosperous life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 13'),
('YOGA_AMSAVATARA','AUSPICIOUS',N'Spotless fame, wide learning, passions kept in check; an authority on philosophy, a ruler or equal to one.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 50'),
('YOGA_ANAPATHYA','INAUSPICIOUS',N'Childlessness.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 211'),
('YOGA_ANAPHA','AUSPICIOUS',N'Well-formed body, dignified presence, good name, generous and self-respecting; turns to renunciation in later life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 3'),
('YOGA_ANDHA','INAUSPICIOUS',N'Poor eyesight at night, or blindness from birth.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 165, 288-289'),
('YOGA_ANGAHEENA','INAUSPICIOUS',N'Loss of limbs.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 285'),
('YOGA_ANNADANA','AUSPICIOUS',N'Hospitable; feeds many people.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 171'),
('YOGA_APAKEERTI','INAUSPICIOUS',N'Bad reputation.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 244'),
('YOGA_APUTRA','INAUSPICIOUS',N'Childlessness.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 224'),
('YOGA_ARDHA_CHANDRA','AUSPICIOUS',N'Fair features; happy throughout life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 79'),
('YOGA_ASATYAVADI','INAUSPICIOUS',N'Given to lying.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 157'),
('YOGA_AYATNA_DHANA_LABHA','AUSPICIOUS',N'Wealth comes with little effort.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 143'),
('YOGA_AYATNA_GRIHA_PRAPTA','AUSPICIOUS',N'Gets substantial house property with hardly any effort.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 189-190'),
('YOGA_BAHU_STREE','MIXED',N'Many wives or partners.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 238'),
('YOGA_BAHUDRAVYARJANA','AUSPICIOUS',N'Earns a great deal of money and builds a fortune.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 129'),
('YOGA_BAHUPUTRA','AUSPICIOUS',N'Many children.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 220-221'),
('YOGA_BANDHANA','INAUSPICIOUS',N'Imprisonment.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 271'),
('YOGA_BANDHU_PUJYA','AUSPICIOUS',N'Respected by relatives and friends.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 193-194'),
('YOGA_BANDHUBHISTHYAKTHA','INAUSPICIOUS',N'Deserted by relatives.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 195'),
('YOGA_BHADRA','AUSPICIOUS',N'Strong, well-built and reserved; helps relatives and lives to a good old age.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 23'),
('YOGA_BHAGA_CHUMBANA','MIXED',N'A particular sensual habit; describes temperament more than fortune.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 240'),
('YOGA_BHAGYA','AUSPICIOUS',N'Very fortunate, pleasure-loving and rich.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 241'),
('YOGA_BHARATHI','AUSPICIOUS',N'Famous scholar, fond of music, attractive and religious.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 29'),
('YOGA_BHARYASAHA_VYABHICHARA','INAUSPICIOUS',N'Both spouses are unfaithful.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 282'),
('YOGA_BHASKARA','AUSPICIOUS',N'Wealthy, brave and cultured; learned in scriptures, astrology and music.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 159'),
('YOGA_BHERI','AUSPICIOUS',N'Long-lived and healthy, many sources of income; happiness from spouse and children; generous and religious.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 45'),
('YOGA_BHOJANA_SOUKHYA','AUSPICIOUS',N'Rich; always has good food.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 170'),
('YOGA_BHRATRUSAPA_SUTAKSHAYA','INAUSPICIOUS',N'Loss of children traced to a sibling''s curse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 218'),
('YOGA_BHRATRUVRIDDHI','AUSPICIOUS',N'Happiness through siblings, who prosper greatly.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 177'),
('YOGA_BRAHMA','AUSPICIOUS',N'Fine food, respected by the learned, highly educated, long-lived and charitable.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 63'),
('YOGA_BUDDHI_JADA','INAUSPICIOUS',N'Dull intellect.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 233'),
('YOGA_BUDDHIMATURYA','AUSPICIOUS',N'Great intelligence and character.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 231'),
('YOGA_BUDHA','AUSPICIOUS',N'Comforts, power and fame; learned, intelligent and free of enemies.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 162'),
('YOGA_BUDHA_ADITYA','AUSPICIOUS',N'Very intelligent and skilful; good reputation, respect and comfort.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 24'),
('YOGA_CHANDIKA','AUSPICIOUS',N'Assertive, charitable and wealthy; a minister or equal; long, happy life and fame.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 57'),
('YOGA_CHANDRA','AUSPICIOUS',N'A ruler or equal to one; commands respect, earns and spends well.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 80'),
('YOGA_CHANDRA_MANGALA','INAUSPICIOUS',N'Earnings by unscrupulous means; harsh to mother and relatives.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 6'),
('YOGA_CHAPA','AUSPICIOUS',N'Wealthy and strong; serves in high councils or handles a treasury.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 30, 78'),
('YOGA_CHATUSSAGARA','AUSPICIOUS',N'Good reputation, standing equal to a ruler; long prosperous life, good children and health; far-reaching fame.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 8'),
('YOGA_CHHATRA','AUSPICIOUS',N'A happy life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 77'),
('YOGA_DAMNI','AUSPICIOUS',N'Very charitable; helps others.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 92'),
('YOGA_DANDA','INAUSPICIOUS',N'Lacks happiness from spouse and children.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 74'),
('YOGA_DARIDRA','INAUSPICIOUS',N'Heavy debts and poverty; mean conduct.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 104, 144-153'),
('YOGA_DATTAPUTRA','MIXED',N'Children come through adoption.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 222-223'),
('YOGA_DEHAKASHTA','INAUSPICIOUS',N'Lacks bodily comfort.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 110'),
('YOGA_DEHAPUSHTI','AUSPICIOUS',N'Well-built body, happiness and riches.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 109'),
('YOGA_DEHASTHOULYA','MIXED',N'A heavy, stout body.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 114-116'),
('YOGA_DEVENDRA','AUSPICIOUS',N'Handsome, of spotless reputation; commands and builds; good longevity.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 55'),
('YOGA_DHANA','AUSPICIOUS',N'Acquires much wealth.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 118-128, 130-137, 139-142'),
('YOGA_DHATRUTWA','AUSPICIOUS',N'Very generous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 243'),
('YOGA_DURADHARA','AUSPICIOUS',N'Bountiful; plenty of wealth and conveyances.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 4'),
('YOGA_DURMARANA','INAUSPICIOUS',N'Unnatural death.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 274'),
('YOGA_DURMUKHA','INAUSPICIOUS',N'Unattractive face; irritable temper.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 168-169'),
('YOGA_DURYOGA','INAUSPICIOUS',N'Effort goes unrewarded; looked down on, self-seeking; lives away from home.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 103'),
('YOGA_DWADASA_SAHODARA','MIXED',N'Born into a very large set of siblings.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 180'),
('YOGA_EKAPUTRA','MIXED',N'Only one son.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 225'),
('YOGA_GADA','AUSPICIOUS',N'Religious and wealthy.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 81'),
('YOGA_GAJA','AUSPICIOUS',N'Happy and rich throughout life; commands animals and conveyances.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 48'),
('YOGA_GAJAKESARI','AUSPICIOUS',N'Many relations, polite and generous; holds local authority; lasting reputation.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 1'),
('YOGA_GALAKARNA','INAUSPICIOUS',N'Ear troubles.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 264'),
('YOGA_GANDHARVA','AUSPICIOUS',N'Outstanding skill in the fine arts; strong, well-dressed and famous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 60'),
('YOGA_GARUDA','AUSPICIOUS',N'Respected by the pious, refined speech, feared by enemies; one danger from poison.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 66'),
('YOGA_GAURI','AUSPICIOUS',N'Respectable family and lands; charitable and religious; good children; praised by all.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 28'),
('YOGA_GO','AUSPICIOUS',N'Respectable family; wealthy, strong and of high standing.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 67'),
('YOGA_GOHANTA','INAUSPICIOUS',N'Earns by slaughter.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 300'),
('YOGA_GOLA','AUSPICIOUS',N'Polite and learned; local authority; long-lived.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 68'),
('YOGA_GOLA_SANKHYA','INAUSPICIOUS',N'Poverty, ignorance and idleness.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 97'),
('YOGA_GRIHANASA','INAUSPICIOUS',N'Loses house property.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 191-192'),
('YOGA_GUHYAROGA','INAUSPICIOUS',N'Diseases of the private parts.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 284'),
('YOGA_HALA','MIXED',N'Livelihood through agriculture.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 87'),
('YOGA_HAMSA','AUSPICIOUS',N'Handsome, liked by others, righteous and pure-minded.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 19'),
('YOGA_HARIHARA_BRAHMA','AUSPICIOUS',N'Learned, truthful and pleasant-spoken; conquers enemies and does good deeds.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 51'),
('YOGA_HARSHA','AUSPICIOUS',N'Fortunate, happy, strong, wealthy and famous; overcomes rivals.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 105'),
('YOGA_INDRA','AUSPICIOUS',N'Very brave, lasting fame and high status; enjoyment, but a shorter life is indicated.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 64'),
('YOGA_ISHU','AUSPICIOUS',N'Success as head of an institution such as a prison.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 72'),
('YOGA_JADA','INAUSPICIOUS',N'Nervous in public.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 158'),
('YOGA_JANANAT_PURVAM_PITRU_MARANA','INAUSPICIOUS',N'Father dies before the birth.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 242'),
('YOGA_JARA','INAUSPICIOUS',N'Extramarital relations.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 236'),
('YOGA_JARAJA_PUTRA','INAUSPICIOUS',N'Lacks procreative power; the son is fathered by another.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 237'),
('YOGA_JAYA','AUSPICIOUS',N'Happy, victorious over enemies, successful in ventures and long-lived.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 58'),
('YOGA_KAHALA','MIXED',N'Bold and stubborn but not well informed; heads a small force or area.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 15'),
('YOGA_KALANIDHI','AUSPICIOUS',N'Good-natured, honoured by rulers, owns conveyances and comforts; free of disease.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 49'),
('YOGA_KALANIRDESAT_PUTRA','AUSPICIOUS',N'A son is born at a specific age (32nd, 33rd or 40th year).',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 227-228'),
('YOGA_KALANIRDESAT_PUTRANASA','INAUSPICIOUS',N'Loss of children at specific ages (32nd and 40th years).',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 229-230'),
('YOGA_KALATRASHANDA','INAUSPICIOUS',N'Coldness in the marriage.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 267'),
('YOGA_KAMALA','AUSPICIOUS',N'High prestige, wide fame and many virtues, though not great wealth.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 88'),
('YOGA_KAPATA','INAUSPICIOUS',N'Hypocrisy.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 202-204'),
('YOGA_KARASCHEDA','INAUSPICIOUS',N'Injury to the hands.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 272'),
('YOGA_KEDARA','AUSPICIOUS',N'Livelihood through agriculture; very helpful to others.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 94'),
('YOGA_KEMADRUMA','INAUSPICIOUS',N'Poverty, sorrow and dependence; unrighteous conduct.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 5'),
('YOGA_KHALWATA','INAUSPICIOUS',N'Baldness.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 295'),
('YOGA_KRISANGA','INAUSPICIOUS',N'Lean, emaciated body and bodily pains.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 112-113'),
('YOGA_KSHAYAROGA','INAUSPICIOUS',N'Wasting disease of the lungs (tuberculosis).',N'SRC_RAMAN_300_COMBINATIONS',N'combination 270'),
('YOGA_KULAVARDHANA','AUSPICIOUS',N'An unbroken family line; wealthy, healthy and long-lived.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 70'),
('YOGA_KURMA','AUSPICIOUS',N'Wide fame, princely enjoyments; righteous, brave, helpful and a leader.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 54'),
('YOGA_KUSHTAROGA','INAUSPICIOUS',N'Skin disease (leprosy).',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 268-269'),
('YOGA_KUSUMA','AUSPICIOUS',N'A ruler or equal; protects kin, founds or heads a town; spotless reputation.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 52'),
('YOGA_KUTA','INAUSPICIOUS',N'Untruthful; works as a jailor.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 76'),
('YOGA_LAKSHMI','AUSPICIOUS',N'Wealthy, noble, learned, of high integrity and reputation; enjoys every comfort.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 27'),
('YOGA_MAHABHAGYA','AUSPICIOUS',N'Good character, liberal and famous; a ruler or equal; long life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 25'),
('YOGA_MAKUTA','MIXED',N'Powerful leader and sportsman, but of harsh disposition.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 56'),
('YOGA_MALAVYA','AUSPICIOUS',N'Strong body and mind; wealthy, happy with spouse and children; owns vehicles; learned and renowned.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 20'),
('YOGA_MALIKA_BHAGYA','AUSPICIOUS',N'Religious, well-to-do, mighty and good.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 40'),
('YOGA_MALIKA_DHANA','AUSPICIOUS',N'Very wealthy, dutiful and resolute, but unsympathetic.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 33'),
('YOGA_MALIKA_KALATRA','AUSPICIOUS',N'Influential; attractive to the opposite sex.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 38'),
('YOGA_MALIKA_KARMA','AUSPICIOUS',N'Respected and virtuous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 41'),
('YOGA_MALIKA_LABHA','AUSPICIOUS',N'Skilful; a lovely spouse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 42'),
('YOGA_MALIKA_LAGNA','AUSPICIOUS',N'A ruler or commander; wealthy.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 32'),
('YOGA_MALIKA_PUTRA','AUSPICIOUS',N'Highly religious and famous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 36'),
('YOGA_MALIKA_RANDHRA','INAUSPICIOUS',N'Poverty; dominated by the spouse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 39'),
('YOGA_MALIKA_SATRU','INAUSPICIOUS',N'Greedy and somewhat poor.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 37'),
('YOGA_MALIKA_SUKHA','AUSPICIOUS',N'Charitable and wealthy.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 35'),
('YOGA_MALIKA_VIKRAMA','MIXED',N'Rich and in command, surrounded by brave people, but sickly.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 34'),
('YOGA_MALIKA_VYAYA','AUSPICIOUS',N'Honoured, liberal and respected.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 43'),
('YOGA_MARUD','AUSPICIOUS',N'Good talker, large-hearted, rich and learned; successful in business.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 160'),
('YOGA_MATIBHRAMANA','INAUSPICIOUS',N'Mental derangement.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 291-294'),
('YOGA_MATRU_DEERGHAYUR','AUSPICIOUS',N'Mother lives long.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 196-197'),
('YOGA_MATRU_SATRUTWA','INAUSPICIOUS',N'Hostility towards the mother.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 207'),
('YOGA_MATRU_SNEHA','AUSPICIOUS',N'Warm relations with the mother.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 208'),
('YOGA_MATRUGAMI','INAUSPICIOUS',N'Gravely improper conduct toward the mother.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 200'),
('YOGA_MATRUMOOLA_DHANA','AUSPICIOUS',N'Earns money with the mother''s help.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 138'),
('YOGA_MATRUNASA','INAUSPICIOUS',N'Early loss of the mother.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 198-199'),
('YOGA_MATRUSAPA_SUTAKSHAYA','INAUSPICIOUS',N'Loss of children traced to the mother''s curse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 217'),
('YOGA_MATSYA','AUSPICIOUS',N'Loving, good-natured, of strong character; famous, religious and learned.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 53'),
('YOGA_MOOKA','INAUSPICIOUS',N'Impaired speech.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 163'),
('YOGA_MRIDANGA','AUSPICIOUS',N'Respected by rulers; famous, attractive and influential.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 46'),
('YOGA_MUSALA','AUSPICIOUS',N'Self-respecting, wealthy, learned and steady; famous and proud.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 99'),
('YOGA_NALA','INAUSPICIOUS',N'Physical defect; shrewd but flawed.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 100'),
('YOGA_NAV','MIXED',N'Happy at times and famous, but miserly.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 75'),
('YOGA_NETRANASA','INAUSPICIOUS',N'Loss of eyesight, attributed to the displeasure of those in power.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 164'),
('YOGA_NISHKAPATA','AUSPICIOUS',N'Pure-hearted; dislikes secrecy and hypocrisy.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 205-206'),
('YOGA_NISHTURABHASHI','INAUSPICIOUS',N'Harsh speech.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 296'),
('YOGA_PARAKRAMA','AUSPICIOUS',N'Great courage.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 182'),
('YOGA_PARANNABHOJANA','INAUSPICIOUS',N'Lives on others'' food; dependence.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 172'),
('YOGA_PARIHASAKA','AUSPICIOUS',N'Witty, humorous speaker.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 156'),
('YOGA_PARIJATHA','AUSPICIOUS',N'Happy in middle and later life; honoured by rulers, traditional, generous and famous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 47'),
('YOGA_PARVATA','AUSPICIOUS',N'Wealthy, prosperous, liberal and charitable; heads a town or village.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 14'),
('YOGA_PASA','AUSPICIOUS',N'Wealth by right means; surrounded by friends, staff and relatives.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 93'),
('YOGA_PEENASAROGA','INAUSPICIOUS',N'Chronic nasal inflammation.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 278'),
('YOGA_PISACHA_GRASTHA','INAUSPICIOUS',N'Troubled by unseen afflictions (''spirits'').',N'SRC_RAMAN_300_COMBINATIONS',N'combination 287'),
('YOGA_PITRUSAPA_SUTAKSHAYA','INAUSPICIOUS',N'Loss of children traced to the father''s anger.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 216'),
('YOGA_PITTAROGA','INAUSPICIOUS',N'Bilious complaints.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 279'),
('YOGA_PRETASAPA','INAUSPICIOUS',N'Loss of children attributed to ancestral curses.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 219'),
('YOGA_PUSHKALA','AUSPICIOUS',N'Wealthy, sweet-spoken, famous and honoured by those in power.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 26'),
('YOGA_PUTRA_KALATRA_HEENA','INAUSPICIOUS',N'Deprived of spouse and children.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 281'),
('YOGA_PUTRA_SUKHA','AUSPICIOUS',N'Happiness through children.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 235'),
('YOGA_RAJA','AUSPICIOUS',N'Rise to power and royal status, even from an ordinary family.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 245-263'),
('YOGA_RAJA_BHANGA','INAUSPICIOUS',N'Born to privilege but loses fortune and position.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 298-299'),
('YOGA_RAJABHRASHTA','INAUSPICIOUS',N'A fall from high position.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 297'),
('YOGA_RAJALAKSHANA','AUSPICIOUS',N'Attractive appearance and the qualities of eminent people.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 10'),
('YOGA_RAJJU','MIXED',N'Fond of travel and handsome; seeks wealth abroad; somewhat cruel and envious.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 98'),
('YOGA_RAVI','AUSPICIOUS',N'Respected by rulers, learned in sciences; fame after the 15th year.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 65'),
('YOGA_ROGAGRASTHA','INAUSPICIOUS',N'Weak constitution; sickly.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 111'),
('YOGA_RUCHAKA','AUSPICIOUS',N'Strong and famous; learned, high status, wealthy, long-lived; a leader.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 22'),
('YOGA_SADA_SANCHARA','MIXED',N'Almost always on the move; a wanderer.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 117'),
('YOGA_SAHODAREE_SANGAMA','INAUSPICIOUS',N'Gravely improper conduct within the family.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 201'),
('YOGA_SAKATA','INAUSPICIOUS',N'Poverty and unhappy domestic life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 82'),
('YOGA_SAKATA_LUNAR','INAUSPICIOUS',N'Fortune lost and regained; ordinary life with poverty and hardship; disliked by relatives.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 12'),
('YOGA_SAKTI','INAUSPICIOUS',N'Lazy, short of money and disliked.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 73'),
('YOGA_SAMUDRA','AUSPICIOUS',N'A ruler or lives like one, free of care.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 90'),
('YOGA_SANGHATAKA_MARANA','INAUSPICIOUS',N'Death in a mass event alongside others.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 276-277'),
('YOGA_SANKHA','AUSPICIOUS',N'Blessed with spouse, children and lands; humane, righteous and learned; long life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 44'),
('YOGA_SAPTHASANKHYA_SAHODARA','MIXED',N'Seven brothers.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 181'),
('YOGA_SARALA','AUSPICIOUS',N'Long-lived, fearless, learned, celebrated and prosperous; a terror to enemies.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 106'),
('YOGA_SARASWATHI','AUSPICIOUS',N'Poet, famous and learned in all sciences; rich and praised; good spouse and children.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 161'),
('YOGA_SAREERA_SOUKHYA','AUSPICIOUS',N'Long life, wealth and favour from authorities.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 108'),
('YOGA_SARPA','INAUSPICIOUS',N'Miserable in many ways; cruel and dull.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 102'),
('YOGA_SARPAGANDA','INAUSPICIOUS',N'Danger of snakebite.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 174'),
('YOGA_SARPASAPA','INAUSPICIOUS',N'Loss of children attributed to the serpent curse.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 212-215'),
('YOGA_SASA','MIXED',N'Commands good staff and may rise to high status, but of questionable character and covets others'' wealth.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 21'),
('YOGA_SATKALATRA','AUSPICIOUS',N'A noble, virtuous spouse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 239'),
('YOGA_SATKATHADI_SRAVANA','AUSPICIOUS',N'Drawn to fine literature and religious discourse.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 186'),
('YOGA_SIRACHCHEDA','INAUSPICIOUS',N'Violent death by beheading.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 273'),
('YOGA_SISNAVYADHI','INAUSPICIOUS',N'Serious sexual disease.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 266'),
('YOGA_SIVA','AUSPICIOUS',N'Big trader and commander; wisdom and a virtuous life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 61'),
('YOGA_SRADDHANNABHUKTHA','INAUSPICIOUS',N'Lives on food from funeral rites.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 173'),
('YOGA_SREENATHA','AUSPICIOUS',N'Pleasant speaker, godly; good spouse and children; loved by all.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 31'),
('YOGA_SRIK','AUSPICIOUS',N'Lives in comfort with conveyances and many enjoyments.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 101'),
('YOGA_SRINGHATAKA','AUSPICIOUS',N'Happy in later life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 86'),
('YOGA_SULA','INAUSPICIOUS',N'Short of wealth; courageous but cruel; scarred by conflict.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 95'),
('YOGA_SUMUKHA','AUSPICIOUS',N'Attractive, smiling face.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 166-167'),
('YOGA_SUNAPHA','AUSPICIOUS',N'Self-earned property; intelligent and wealthy; ruler-like standing and good reputation.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 2'),
('YOGA_SUPUTRA','AUSPICIOUS',N'A worthy son.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 226'),
('YOGA_SWETAKUSHTA','INAUSPICIOUS',N'White skin patches (leucoderma).',N'SRC_RAMAN_300_COMBINATIONS',N'combination 286'),
('YOGA_THEEVRABUDDHI','AUSPICIOUS',N'Precocious intelligence.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 232'),
('YOGA_THRIKALAGNANA','AUSPICIOUS',N'Insight into past, present and future.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 234'),
('YOGA_THRILOCHANA','AUSPICIOUS',N'Great wealth and intelligence; feared by enemies; good longevity.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 69'),
('YOGA_UBHAYACHARI','AUSPICIOUS',N'Eloquent and well-built; liked by all, wealthy and famous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 18'),
('YOGA_UTTAMA_GRIHA','AUSPICIOUS',N'Owns good houses.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 187'),
('YOGA_VAHANA','AUSPICIOUS',N'Material comforts and vehicles.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 209-210'),
('YOGA_VAJRA','AUSPICIOUS',N'Happy and handsome.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 84'),
('YOGA_VAKCHALANA','INAUSPICIOUS',N'Stammering.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 175'),
('YOGA_VALLAKI','AUSPICIOUS',N'Many friends, fond of music and arts; learned, happy and famous.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 91'),
('YOGA_VAMSACHEDA','INAUSPICIOUS',N'The family line ends.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 283'),
('YOGA_VANCHANA_CHORA_BHEETHI','INAUSPICIOUS',N'Constant suspicion; fears being cheated or robbed.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 11'),
('YOGA_VAPEE','MIXED',N'Hoards money.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 89'),
('YOGA_VASI','AUSPICIOUS',N'Happy, prosperous, liberal; favoured by those in power.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 17'),
('YOGA_VASUMATHI','AUSPICIOUS',N'Independent; always has plenty of wealth.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 9'),
('YOGA_VATHAROGA','INAUSPICIOUS',N'Wind (vata) disorders.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 290'),
('YOGA_VESI','AUSPICIOUS',N'Fortunate, happy, virtuous, famous and distinguished.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 16'),
('YOGA_VICHITRA_SAUDHA_PRAKARA','AUSPICIOUS',N'Owns many mansions.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 188'),
('YOGA_VIDYUT','AUSPICIOUS',N'Charitable and pleasure-loving; controls wealth; a ruler or equal.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 59'),
('YOGA_VIHAGA','INAUSPICIOUS',N'Restless wanderer; quarrelsome and petty.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 83'),
('YOGA_VIKALANGA_PATNI','INAUSPICIOUS',N'Spouse has a physical deformity.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 280'),
('YOGA_VIMALA','AUSPICIOUS',N'Frugal, happy, independent and noble.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 107'),
('YOGA_VISHAPRAYOGA','INAUSPICIOUS',N'Danger of poisoning by others.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 176'),
('YOGA_VISHNU','AUSPICIOUS',N'An enjoyable life with fortune from many lands; strong, articulate, devout and honoured; long, healthy life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 62'),
('YOGA_VRANA','INAUSPICIOUS',N'Malignant disease (cancer).',N'SRC_RAMAN_300_COMBINATIONS',N'combination 265'),
('YOGA_YAVA','AUSPICIOUS',N'Happy in middle life.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 85'),
('YOGA_YUDDHA_PRAVEENA','AUSPICIOUS',N'Capable strategist; skilled in conflict.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 183'),
('YOGA_YUDDHATPASCHAT_DRIDHA','AUSPICIOUS',N'Courage grows once the fight has begun.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 185'),
('YOGA_YUDDHATPOORVA_DRIDHACHITTA','AUSPICIOUS',N'Courageous before a fight begins.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 184'),
('YOGA_YUDDHE_MARANA','INAUSPICIOUS',N'Death in battle.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 275'),
('YOGA_YUGA','INAUSPICIOUS',N'Poverty and social exclusion; unorthodox and given to drink.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 96'),
('YOGA_YUKTHI_SAMANWITHAVAGMI','AUSPICIOUS',N'Eloquent, skilful speaker.',N'SRC_RAMAN_300_COMBINATIONS',N'combinations 154-155'),
('YOGA_YUPA','AUSPICIOUS',N'Liberal, self-possessed and charitable.',N'SRC_RAMAN_300_COMBINATIONS',N'combination 71'),
('YOGA_ASUBHA','INAUSPICIOUS',N'Many desires; sinful, and enjoys others'' wealth.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_SUBHA','AUSPICIOUS',N'Eloquence, good looks and good character.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_BASIC_RAJA','AUSPICIOUS',N'Power and prosperity through the joined blessings of kendra and trikona lords.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_BRAHMA_TRIMURTI','AUSPICIOUS',N'Happy and learned; blessed with wealth and children.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_CHAMARA','AUSPICIOUS',N'A ruler or honoured by rulers; long-lived, scholarly, eloquent and skilled in many arts.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_DHARMA_KARMADHIPATI','AUSPICIOUS',N'Sincere, devoted, righteous and fortunate; the finest Raja Yoga.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_GURU_MANGALA','AUSPICIOUS',N'Righteous and energetic; energy goes into dharmic paths.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_HARA','AUSPICIOUS',N'Happy and learned; blessed with wealth and children.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_HARI','AUSPICIOUS',N'Happy and learned; blessed with wealth and children.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_KHADGA','AUSPICIOUS',N'Skilful, wealthy, learned, fortunate and mighty.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_LAGNAADHI','AUSPICIOUS',N'A great person; learned and happy.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_MAALA','AUSPICIOUS',N'Comfort, conveyances and many enjoyments.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_RAJA_ADVANCED','AUSPICIOUS',N'Power and prosperity; one rises to be the best in some field.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_RAJA_SAMBANDHA','AUSPICIOUS',N'Power and prosperity through links between the karakas and the lords of the key houses.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_SAARADA','AUSPICIOUS',N'Wealth, spouse and children; happy, learned and principled; a devoted seeker of knowledge.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_VIPAREETA_RAJA','AUSPICIOUS',N'Great success, usually after an initial struggle.',N'SRC_PVR_INTEGRATED',N'ch.11'),
('YOGA_ANIVAHUPPU','CONTEXTUAL',N'Structural pattern only; no source states its result. Read it with the planets involved.',NULL,NULL);

UPDATE r SET OutcomeNatureCode = n.Nature, InferenceText = n.Inference,
             InferenceSourceRefCode = n.SourceRefCode, InferenceSourceLocator = n.SourceLocator
FROM dbo.tbl_Rule_Yoga r JOIN @n n ON n.YogaCode = r.YogaCode;

IF EXISTS (SELECT 1 FROM dbo.tbl_Rule_Yoga WHERE OutcomeNatureCode IS NULL OR InferenceText IS NULL)
    THROW 51000, 'Every tbl_Rule_Yoga row needs an outcome nature and an inference.', 1;

COMMIT TRANSACTION;
GO

CREATE OR ALTER VIEW dbo.vw_ChartYogaEvaluations
AS
SELECT c.BirthDetailId,b.Name,y.ChartResultId,y.RuleSetId,
       y.SourceRefCode,y.SourceVariantCode,y.YogaCode,y.SourceLocator,
       y.Present,y.EvaluationStatus,y.MissingRequirementCodesJson,
       y.SubjectSex,y.IsNightBirth,y.ElongationDegrees,
       y.IsWaxingMoon,y.IsFullMoon,y.LunarPhasePolicyCode,
       y.SunriseMethodCode,y.Notes,y.ComputedAtUtc,
       COALESCE(rSrc.FormationFamilyCode,rGen.FormationFamilyCode) AS YogaTypeCode,
       COALESCE(rSrc.ShortFormationRule,rGen.ShortFormationRule) AS YogaRule,
       v.YogaSetCode,s.DisplayName AS YogaSetName,v.DisplayName AS VariantDisplayName,
       COALESCE(rSrc.OutcomeNatureCode,rGen.OutcomeNatureCode) AS OutcomeNatureCode,
       COALESCE(rSrc.InferenceText,rGen.InferenceText) AS InferenceText,
       COALESCE(rSrc.InferenceSourceRefCode,rGen.InferenceSourceRefCode) AS InferenceSourceRefCode,
       COALESCE(rSrc.InferenceSourceLocator,rGen.InferenceSourceLocator) AS InferenceSourceLocator
FROM dbo.tbl_Fact_YogaInputEvaluations y
JOIN dbo.tbl_ChartResults c ON c.Id=y.ChartResultId
JOIN dbo.tbl_BirthDetails b ON b.Id=c.BirthDetailId
LEFT JOIN dbo.tbl_Rule_Yoga rSrc ON rSrc.YogaCode=y.YogaCode AND rSrc.RuleSetId=y.RuleSetId AND rSrc.SourceRefCode=y.SourceRefCode
LEFT JOIN dbo.tbl_Rule_Yoga rGen ON rGen.YogaCode=y.YogaCode AND rGen.RuleSetId=y.RuleSetId AND rGen.SourceRefCode IS NULL
LEFT JOIN dbo.tbl_Rule_YogaVariant v ON v.RuleSetId=y.RuleSetId AND v.SourceRefCode=y.SourceRefCode AND v.SourceVariantCode=y.SourceVariantCode
LEFT JOIN dbo.tbl_Dim_YogaSets s ON s.Code=v.YogaSetCode;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SchemaMigrations WHERE ScriptName='159_seed_yoga_outcome_nature_and_inference.sql')
    INSERT dbo.SchemaMigrations (ScriptName,Note)
    VALUES ('159_seed_yoga_outcome_nature_and_inference.sql','Yoga OutcomeNatureCode + InferenceText for all 234 yogas (Raman 300 Combinations / PVR ch.11); exposed in vw_ChartYogaEvaluations');
GO
PRINT '159 applied: yoga outcome nature and inference.';
